### ISSUE TITLE
How to test that PHP can pull data from the database with PDO?

### ISSUE THREAD

**Issue by brendanlawton** [celsocelante/docker-lamp#3]
I've tried creating a Dockerfile for PHP that looks like this:

```
FROM php:7.2-apache
RUN docker-php-ext-install pdo_mysql
```

...and then adjusting the docker-compose.yml accordingly:

```
web:
   build: .
```

But still I get 'connection refused'

Index file looks like:

```
try{
    $db = new pdo('mysql:host=db:8889;dbname=database', 'root', 'root');
}catch(Exception $e){
    echo $e -> getmessage();
}
```

tried both admin and root credentials specified in yml file. I've also tried 127.0.0.1 in place of db.

**Comment by brendanlawton** [comment]
Index file looks like:

```
try{
    $db = new pdo('mysql:host=127.0.0.1:8889;dbname=database', 'admin', 'test');
}catch(Exception $e){
    echo $e -> getmessage();
}
```

**Comment by brendanlawton** [comment]
I found the answer to this by having a look through the phpinfo() output. I hardcoded the DB_PORT value under the Environment section into the host of the pdo connection. I assume there are smarter ways of finding this out using docker and environment variables.

**Comment by celsocelante** [comment]
Thank you, Brendan. I'm gonna take a closer look at this issue later this week.
